#!/usr/bin/env bash
# Ultroid - UserBot
# Copyright (C) 2021-2023 TeamUltroid
#
# This file is a part of < https://github.com/TeamUltroid/Ultroid/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/TeamUltroid/Ultroid/blob/main/LICENSE/>.


echo "
            ┏┳┓╋┏┓╋╋╋╋┏┓┏┓
            ┃┃┣┓┃┗┳┳┳━╋╋┛┃
            ┃┃┃┗┫┏┫┏┫╋┃┃╋┃
            ┗━┻━┻━┻┛┗━┻┻━┛

      Visit @TheUltroid for updates!!

"
# Run both commands
python3 clever.py

# Source environment variables from .env file if it exists
if [ -f .env ]; then
    set -o allexport
    source .env
    set +o allexport
fi

# Check for the SESSION1 variable
if [ "$SESSION1" ]; then
    # If SESSION1 exists, download a script and run it
    wget https://gist.github.com/1Danish-00/6554f034549197e5824972b01f631e0c/raw/main.py -O script.py
    python3 script.py
else
    # If SESSION1 doesn't exist, run pyUltroid
    python3 -m pyUltroid
fi
